---
# Site settings
site_name: PyCon DE & PyData
site_url: https://pioneershub.github.io/pyconde-conference/
site_author: [
  "Alexander Hendorf",
]
site_description: >-
  Docs for organizing our volunteer-driven event.

# Repository at GitHub
repo_name: PioneersHub/pyconde-conference
repo_url: https://github.com/PioneersHub/pyconde-conference

# Copyright for footer
copyright:
  start_year: 2024
  owner: Python Software Verband e.V. / Pioneers Hub gGmbH

# Event details
event:
  event_name: "PyCon DE & PyData 2026"
  start_date: "14.04.2026"
  end_date: "16.04.2026"
  day_before: "13.04.2026"
  month: "April"
  year: "2026"
  location: "Darmstadt, Germany"
  contact_email: "info@pycon.de"
  # program
  cfp_open: "19.11.2025"
  cfp_close: "21.12.2025 23:59 CET"
  review_deadline: "28.01.2026"
  cfp_speakers_notifications: "11.02.2026"
  cfp_link: "https://pretalx.com/orga/event/pyconde-pydata-2026/"
  voting_url: "TBA"
  voting_start: "TBA"
  voting_end: "TBA"
  contact_program: "program26@pycon.de"
  # diversity
  financial_aid_open: "19.11.2025"
  financial_aid_close: "18.01.2026 23:59 CET"
  financial_aid_notifications: "11.02.2026"
  financial_aid_form: "https://docs.google.com/forms/d/e/1FAIpQLSevnRImPfQRh2m-Qm5RiCpKW4uWrHeyqDzBvtwDr2R3YGgM6A/viewform"
  financial_aid_regional_countries: "Albania, Algeria, Andorra, Armenia, Austria, Azerbaijan, Belarus, Belgium, Bosnia and Herzegovina, Bulgaria, Croatia, Czech Republic/Czechia, Denmark, Egypt, Estonia, Finland, France, Georgia, Germany, Greece, Hungary, Iceland, Ireland, Israel, Italy, Jordan, Kosovo, Latvia, Lebanon, Libya, Liechtenstein, Lithuania, Luxembourg, Malta, Monaco, Montenegro, Moldova, Morocco, Netherlands, North Macedonia, Northern Cyprus, Norway, Palestine, Poland, Portugal, Republic of Cyprus, Romania, San Marino, Serbia, Slovakia, Slovenia, Spain, Sweden, Switzerland, Syria, Tunisia, Turkey, Ukraine, United Kingdom, and Vatican City."
  # committees
  call_for_committee_open: "09.10.2025"
  call_for_committee_close: "31.10.2025"
  apply_url_committees: "https://pioneershub.typeform.com/to/X4DSSKpG"
  # volunteers
  call_for_volunteers_open: "01.03.2026"
  call_for_volunteers_close: "15.03.2026"
  apply_url_volunteers: "/to-be-announced/"
  # tickets
  ticket_sales_open: "19.11.2025"
  ticket_sales_late_bird: "11.02.2026"

  # Code of Conduct Team
  coc_email: coc-reports@pycon.de
  team_members: |
    - To be announced
    - To be announced
    - To be announced
    - To be announced
  backup_team_members: |
    - To be announced
    - To be announced

committees:
  # Committee names must match the headers in the committees.md file
  # Expected workloads and milestones for each committee
  "coc":
    requirements:
      attend_conference: true
    workload:
      average: "Usually not much to do, but be prepared for reports. If reports come in immediate action is required."
      start: "15.11.2025"
      peak: "During the conference, it depends on reports coming in"
      end: "Until all reports have been resolved"
  "community_support":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "15.11.2024"
      peak: "4 weeks before the conference, during the conference"
      end: "2 weeks afters the conference"
  "communication":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "15.11.2024"
      peak: "3 weeks before the conference, during the conference"
      end: "2 weeks afters the conference"
  "diversity":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "01.11.2025"
      peak: "During the selection and notification process. Four months before the conference 4-5 hours per week for 2 weeks"
      end: "Four weeks after the conference until report and reimbursements are made"
  "experience":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "infrastructure":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "01.11.2025"
      peak: "2 weeks before the conference, during the conference if something breaks"
      end: "conference end"
  "on_site_operations":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "Three months before conference, 1-2 hours a week"
      peak: "Four weeks before the conference 4-5 hours per week. During conference - all day"
      end: "End of the conference"
  "program":
    attend_conference: false
    workload:
      average: "2-3 hours per week"
      start: "Six months before conference, 1-2 hours a week"
      peak: "During review, selection and scheduling. Four months before the conference 4-5 hours per week for 4 weeks."
      end: "End of the conference"
  "steering":
    attend_conference: true
    workload:
      average: "2 - 3 hours per week"
      start: "6 months before the conference, 1-2 hours per week"
      peak: "Onboarding for new committees and major decision process times, 3-4 hours a week"
      end: "End of the conference"
  "swag":
    attend_conference: true
    workload:
      average: "1 hour per week"
      start: "1 month before the ticket sales"
      peak: "4 weeks before the conference, collecting final numbers for order"
      end: "Conference day"
  "video":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "Three months before conference"
      peak: "During the conference"
      end: "Until all videos have been released"

# custom config for social cards customization
social_cards:
  dirs:
    # relative paths from the repository root
    cache_dir: "./.cache/plugin/social"
    site_dir: "./site/assets/images/social"
    # by convention, rename your logo accordingly
  logo_path: "./docs/assets/images/social_card_logo.png"
